### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ikarago** [ikarago/Unigram#1]
A collection of ideas submitted by the community.

These ideas might or might not see the light of day, but until then they'll be stored here for future reference:

**Ideas: (Updated 20-06-2016 12:52 CEST)**

- [ ] Sort option to sort chats
- [ ] Set chats as favourite
- [ ] Set app theme in settings
- [ ] Tap and hold on a chat to mark it as read
- [ ] Use a pivot to swipe between chats?
- [ ] Show multiple notifications on the Live-tile (with Large tile or rotate like in Snips?)
- [ ] Take users to the mention of them in an group when they tap on the notification.
- [ ] Shortcuts on keyboard (Ctrl+Enter for next line, shortcut to search, etc.)
- [ ] Swipable actions in Home (Swipe to Favourite a chat or dismiss all messages as read)
- [ ] The option to have Round or Square profile pictures
- [ ] Option to export chats as an .txt-file or XML-file.
- [ ] Ability to have chats in seperate windows
- [ ] Protect chats and/or app with a password/Windows Hello
- [ ] Download/Upload-list for active uploads and downloads
- [ ] Automatic tags on uploads to easily find download back in the chat (on other platforms)

**Comment by gabrielbutoeru** [comment]
What about fast reply from the notification?

**Comment by ikarago** [comment]
That one is a big one on the wishlist, so I put that one on laat with the UWP-specific features :)

**Comment by dachibox** [comment]
Hi, we need to redact an "How to contribute". Its important once @guerrerotook finish the project organization to describe it and set some guidelines for contribution.

**Comment by Alexmitter** [comment]
Please add: "The option to have Round or Square profile pictures"

**Comment by ikarago** [comment]
@Alexmitter Added!

**Comment by thepaulomalley** [comment]
Possible feature suggestion - the ability to export an entire chat history as a file (eg: doc file)

**Comment by danielsteiner** [comment]
@thepaulomalley Doc is bad. We need something with some markup that is human readable but serializable so you can use them as backup.

**Comment by JuanPZV** [comment]
@danielsteiner Maybe we can just use a plain txt showing the user name, the datetime, and the message. Or use XML/JSON to share the chat between differents unigram.

**Comment by ikarago** [comment]
@thepaulomalley Added the idea! ;)

**Comment by DarthJahus** [comment]
@thepaulomalley, XML would be great, really, like Live Messenger did at the time! XML can handle timestamp and many things, such as emojis and replies! And we can just write a style sheet to make it show correctly on a browser!

**Comment by MateiRadu** [comment]
Design-wise, I think there is some unnecessary repetition on a desktop:
![2016-06-19 12_28_58-unigram alpha](https://cloud.githubusercontent.com/assets/1713151/16176819/f2b4f8fa-3619-11e6-85ba-36435cecdf09.png)

We could do something like the Twitter client, using only the system bar:
![2016-06-19 12_29_06-twitter](https://cloud.githubusercontent.com/assets/1713151/16176824/0add27ea-361a-11e6-97e0-403f5cb607f1.png)

We can do this doing a simple if-state to see if the device is mobile or desktop and loading the correct XAML page accordingly. Of course, the system bar can be coloured.

Finally, when the Desktop is in "Tablet mode" the system bar is hidden. We could show in that case the second bar (of first screenshot) as there are ways to check if the user is in tablet mode or not.

What do you think? :smile:

**Comment by FrayxRulez** [comment]
We need that bar because we will use it in chat view. But instead of "UNIGRAM" we could place a search box

**Comment by MateiRadu** [comment]
@FrayxRulez if we use it for a search feature or anything different from the app name it's fine with me. The important thing is avoiding useless repetition.

Anyway, are you still accepting new Collaborators? I'd like to contribute actively :wink:. I'm a computer science student and I have some experience with C# and in general with UWP.

**Comment by FrayxRulez** [comment]
@MateiRadu join us! https://telegram.me/joinchat/ARAF8wcUwLskZCgotn3kKA
