### ISSUE TITLE
How can I test the app?

### ISSUE THREAD

**Issue by luckv** [ikarago/Unigram#22]
I red that I have to create an app on the telegram site, but whose information should I insert in the form, like the URL of the app? Sorry for my english and my basic errors.
Btw I had already download and I opened the project in Visual Studio, this is the thing I missed

**Comment by d8vjork** [comment]
Official channel for Unigram releases: https://telegram.me/unigramchannel

**Comment by luckv** [comment]
Thank, I have already tried this, but windows said that I can't install the program because I miss a reliable certificate

>Devi installare un nuovo certificato per questo pacchetto dell'app o ti occorre un nuovo pacchetto >dell'app con certificati attendibili. L'amministratore di sistema o lo sviluppatore dell'app può fornire >assistenza. Una catena di certificati è stata elaborata ma è terminata in un certificato radice che non è >attendibile (0x800B0109)

**Comment by FrayxRulez** [comment]
@luckv actually the packages we distribute are installable only on ARM phones

**Comment by luckv** [comment]
@FrayxRulez Ok, I didn't know that
